name: CI Pipeline

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python model/train.py

  docker:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: train

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ihsanezkr/mlops-breast-cancer:latest